---
# tasks file for provision-nix-home-manager
- name: Create nix directories for nix
  ansible.builtin.file:
    path: /nix
    state: directory
    owner: user
    group: user
    mode: '755'

- name: Download Nix installer script
  get_url:
    url: https://nixos.org/nix/install
    dest: /tmp/nix_install.sh
    mode: 0755

- name: Ensure group "nixbld" exists
  ansible.builtin.group:
    name: nixbld
    state: present

- name: Add user to nixbld group
  user:
    name: user
    groups: nixbld
    append: yes

- name: Run nix installer
  shell: /tmp/nix_install.sh
  environment:
    USER: "user"
    ALLOW_PREEXISTING_INSTALLATION: "x"
