---
# tasks file for provision-nix-home-manager
- name: Create nix directories for nix
  ansible.builtin.file:
    path: /nix
    state: directory
    owner: user
    group: user
    mode: '755'

- name: Download Nix installer script
  get_url:
    url: https://nixos.org/nix/install
    dest: /tmp/nix_install.sh
    mode: 0755

# - name: Install nix
#   ansible.builtin.shell:
#     cmd: sh <(curl -L https://nixos.org/nix/install) --no-daemon
